### PR TITLE
Add Connected Textures

### LINKED ISSUE #3: Fix IE Rendering Bug

### PR DESCRIPTION
**Pull request by Krutonium**
Fixes #3 - In theory. I cannot test it as I have no examples. Please Verify, @HazmatDrone

### CODE REVIEW

**Comment by Krutonium** [comment]
@HazmatDrone

**Review by HazmatDrone — CHANGES_REQUESTED** [review]
Did not fix anything.

**Comment by Krutonium** [comment]
Then I have no idea.

**Comment by HazmatDrone** [comment]
Does this benefit the modpack; do any mods utilise it? Or should we just close and delete the branch?

**Comment by Krutonium** [comment]
As far as I could tell when I added it, it didn't work whatsoever.

**Pull request closed without merging**
