### PR TITLE
Player now spawns in Forest

### PR DESCRIPTION
**Pull request by Krutonium**
@HazmatDrone Please see if there's any other settings you want changed.

### CODE REVIEW

**Review by HazmatDrone — COMMENTED** [review]
Did you test it

**Comment by Krutonium** [comment]
No, I'd have to nuke the server world to do so.

**Comment by Krutonium** [comment]
Works in Single Player, however it generates a Portal at the same time, if that's somthing that is a concern.

**Comment by HazmatDrone** [comment]
My concern is that if we spawn in the TF exclusively then it might make some things impossibly hard to do, such as get copper, farm creepers, whatever

**Comment by Krutonium** [comment]
Well the way it is right now, we can go back and forth at will, but we are put in TF by default. You spawn next to the portal.

**Comment by HazmatDrone** [comment]
Meh.

**Pull request closed without merging**
